#!/bin/bash

HOST_IN="$(pwd)/input"
HOST_OUT="$(pwd)/output"

echo $HOST_IN

docker run \
  --mount type=bind,source="$HOST_IN",readonly,target="/home/demo/input" \
  --mount type=bind,source="$HOST_OUT",target="/home/demo/output" \
  lustre-sally
