#!/bin/bash

HOST_IN="$(pwd)/in"
HOST_OUT="$(pwd)/out"

echo $HOST_IN

docker run \
  --mount type=bind,source="$HOST_IN",readonly,target="/home/demo/inputs" \
  --mount type=bind,source="$HOST_OUT",target="/home/demo/outputs" \
  lustre-sally
