packages:
  - '.'
extra-deps:
  - GraphSCC-1.0.4
  - alex-tools-0.4
  - monadLib-3.7.3
  - panic-0.4.0.1
  - simple-get-opt-0.1.0.0
  - simple-smt-0.9.3
  - git: https://github.com/GaloisInc/lustre
    commit: 28c4cdddc46ee989f5075bd00efc89515f18eba3
resolver: lts-12.13
allow-newer: true
