packages:
  - '.'
  - dependencies/lustre
extra-deps:
  - GraphSCC-1.0.4
  - alex-tools-0.4
  - monadLib-3.9
  - panic-0.4.0.1
  - simple-get-opt-0.2.0
  - simple-smt-0.9.4
resolver: lts-12.26
allow-newer: true
