packages:
  - '.'
extra-deps:
  - GraphSCC-1.0.4
  - alex-tools-0.4
  - monadLib-3.7.3
  - panic-0.4.0.1
  - simple-get-opt-0.1.0.0
  - simple-smt-0.9.3
  - git: https://github.com/GaloisInc/lustre
    commit: 55eab39a00660ce04711e6d245dcf2bd9338940e
resolver: lts-12.13
allow-newer: true
